version: '3.3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '8080:8080'
